language: ruby
rvm:
    - 2.2.1

install: 
    - npm install
    - npm install -g bower
    - bundle install
    - rake bower:install

script: 

notifications:
  slack: a-maze-team:KQAj0tr2neVDB38uGAQFcuA6
